/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-primary": "#ffffff",
        "surface-dim": "#dadada",
        "on-error-container": "#93000a",
        "outline-variant": "#e2bfb0",
        "secondary-container": "#e2e2e2",
        "on-secondary-fixed-variant": "#474747",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#a04100",
        "primary-fixed-dim": "#ffb693",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-container": "#2f3132",
        "tertiary-container": "#989999",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#7a3000",
        "surface-container": "#eeeeee",
        "outline": "#8e7164",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#1b1b1b",
        "primary": "#a04100",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#454747",
        "background": "#f9f9f9",
        "primary-container": "#ff6b00",
        "primary-fixed": "#ffdbcc",
        "on-surface-variant": "#5a4136",
        "on-primary-fixed": "#351000",
        "error": "#ba1a1a",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary-container": "#572000",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb693",
        "on-background": "#1a1c1c",
        "tertiary": "#5d5f5f",
        "secondary": "#5e5e5e",
        "on-secondary-container": "#646464"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "container-max-width": "1280px",
        "border-width": "3px",
        "lg": "24px",
        "md": "16px",
        "sm": "8px",
        "xl": "48px",
        "unit": "4px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-xl": ["Bebas Neue"],
        "body-sm": ["Hanken Grotesk"],
        "headline-md": ["Bebas Neue"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Bebas Neue"],
        "headline-xl-mobile": ["Bebas Neue"],
        "label-md": ["Bebas Neue"],
        "label-sm": ["Bebas Neue"],
        "body-lg": ["Hanken Grotesk"],
        "headline-sm": ["Bebas Neue"],
        "headline-lg": ["Bebas Neue"]
      },
      fontSize: {
        "headline-xl": ["96px", { "lineHeight": "90%", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "140%", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "100%", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "150%", "fontWeight": "400" }],
        "headline-lg-mobile": ["40px", { "lineHeight": "95%", "fontWeight": "400" }],
        "headline-xl-mobile": ["56px", { "lineHeight": "90%", "fontWeight": "400" }],
        "label-md": ["16px", { "lineHeight": "100%", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "100%", "letterSpacing": "0.08em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "150%", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "110%", "letterSpacing": "0.03em", "fontWeight": "400" }],
        "headline-lg": ["64px", { "lineHeight": "95%", "letterSpacing": "0em", "fontWeight": "400" }]
      },
      boxShadow: {
        "brutal-primary": "4px 4px 0px 0px #000000",
        "brutal-lg": "6px 6px 0px 0px #000000",
        "brutal-xl": "8px 8px 0px 0px #000000",
        "brutal-hover": "10px 10px 0px 0px #000000",
        "brutal-orange": "4px 4px 0px 0px #ff6b00",
        "brutal-white": "4px 4px 0px 0px #ffffff"
      }
    },
  },
  plugins: [],
}
